services:

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:${HEADSCALE_UI_IMAGE_TAG:-latest}
    restart: unless-stopped
    depends_on:
      - headscale
      - traefik
    networks:
      - internal
    labels:
      - traefik.enable=true

      # Uncomment this if you want to use the UI on same domain as headscale
      #- traefik.http.routers.headscale-ui.rule=Host(`${HEADSCALE_UI_FQDN}`) && PathPrefix(`${HEADSCALE_UI_PATH_PREFIX:-/web}`)

      # Uncomment this if you want to use the UI on a different domain
      - traefik.http.routers.headscale-ui.rule=Host(`${HEADSCALE_UI_FQDN}`) && PathPrefix(`${HEADSCALE_UI_PATH_PREFIX:-/}`)
      - traefik.http.routers.headscale-ui.entrypoints=websecure
      - traefik.http.routers.headscale-ui.tls.certresolver=le
      - traefik.http.routers.headscale-ui.middlewares=headscale-ui-auth
      - traefik.http.middlewares.headscale-ui-auth.basicauth.usersfile=/etc/traefik/users
      - traefik.http.services.headscale-ui.loadbalancer.server.port=8080


