services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_TAG:-latest}
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=false
      - --ping=true
      - --ping.entrypoint=traefik
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:9000
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
      - "3478:3478/udp"  # DERP STUN
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9000/ping || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    environment:
      - TRAEFIK_ACME_DNS01=${TRAEFIK_ACME_DNS01:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/acme.json:/acme.json
    networks:
      - edge
      - internal
    labels:
      - "traefik.enable=true"
      # Optional secure dashboard (disabled by default in static config)
      # See README to enable safely behind basic auth + IP whitelist
      # Explicit HTTP -> HTTPS redirect router for your FQDN (helps ACME trigger)
      - "traefik.http.routers.redirect.rule=Host(`${HEADSCALE_FQDN}`)"
      - "traefik.http.routers.redirect.entrypoints=web"
      - "traefik.http.routers.redirect.middlewares=redirectscheme@docker"
      - "traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect.service=noop@internal"

  headscale:
    image: headscale/headscale:${HEADSCALE_IMAGE_TAG:-latest}
    container_name: headscale
    restart: unless-stopped
    depends_on:
      - traefik
    command: ["serve"]
    environment:
      - HEADSCALE_SERVER_URL=${HEADSCALE_SERVER_URL}
      - HEADSCALE_BASE_DOMAIN=${HEADSCALE_BASE_DOMAIN}
      - HEADSCALE_LISTEN_ADDR=0.0.0.0:8080
      - HEADSCALE_METRICS_LISTEN_ADDR=127.0.0.1:9090
      - HEADSCALE_ACME_ENABLED=false
      - HEADSCALE_DATABASE_URL=${HEADSCALE_DATABASE_URL:-}
      - HEADSCALE_USE_SQLITE=${HEADSCALE_USE_SQLITE:-false}
    volumes:
      - ./data/headscale:/var/lib/headscale
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`${HEADSCALE_FQDN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=le"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"
      - "traefik.http.routers.headscale.middlewares=sec-headers@file,compress@file,rate-limit@file"

# secrets are optional and handled via entrypoint scripts

networks:
  edge:
    driver: bridge
  internal:
    driver: bridge
    internal: true
