api:
  dashboard: false

global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":9000"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: "${TRAEFIK_LOG_LEVEL:-INFO}"

accessLog: {}

certificatesResolvers:
  le:
    acme:
      email: "${ACME_EMAIL}"
      storage: "/acme.json"
      # One of dnsChallenge or httpChallenge can be used
      httpChallenge:
        entryPoint: web
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: false
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"


